version: "3"
services:
  neo4j:
    image: neo4j:4.4.4-community
    ports:
      - 7687:7687
      - 7474:7474
    networks:
      - ***REMOVED***_dev


networks:
  ***REMOVED***_dev:
    external: false
